### ISSUE TITLE
Move to LLNL Org?

### ISSUE THREAD

**Issue by IanLee1521** [tgamblin/libra#3]
Going through a list of OSS projects for IPO, should this move into the LLNL org?

**Comment by tgamblin** [comment]
It's old and unsupported, but I don't mind moving it.  Want me to?  This is basically my Ph.D. project.

**Comment by IanLee1521** [comment]
Eh, if that's what its for, I could go either way. Up to you. I'll probably just add a `repositories.yml` file and have this in the list.

**Comment by tgamblin** [comment]
Most of this is factored out into separate libraries/tools anyway.  Wavelet compression is in `nami`, Callpath representation is in `callpath`, MPI wrapper generation is in `wrap`, parallel clustering library is factored out into `muster`, and the measurement part is superseded by `caliper`.  The only thing unique to this repo is the GUI, which maybe we could salvage parts of but I'm not sure it's that useful on its own.  It's only a prototype.
